# Generated by Django 5.1.3 on 2024-11-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_system_app', '0002_task_status_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
